Player claire;
Player lauren;
Player sophie;
Teacher monroy;
Teacher buch;
Teacher mosko;
Teacher pants;
Teacher mejia;
Teacher valley;
Teacher liu;
Teacher pollo;
Teacher pinto;
Teacher arnold;
Teacher sansy;
Teacher gerstein;
Teacher ryan;
int rx, ry, rw, rh;
int disp;
boolean instr;
boolean choose;
boolean back;
boolean cred;
boolean start;
boolean laure;
boolean clair;
boolean sophi;
boolean first; // boolean for getting to the first floor... this is true when the score is 200
boolean winning; // gets you to the win screen without having to worry about moving out of the rectangle that is APA... I think
boolean play;
PImage floor;
PImage startHall;
PImage mon;
PImage arn;
PImage pan;
PImage mos;
PImage san;
PImage pol;
PImage val;
PImage dr;
PImage mej;
PImage pin;
PImage lu;
PImage ger;
PImage mah;
PImage lucy;
PImage watson;
PImage jenn;
PImage dmon;
PImage darn;
PImage dpan;
PImage dmos;
PImage dsan;
PImage dpol;
PImage dval;
PImage ddr;
PImage dmej;
PImage dpin;
PImage dlu;
int a, b;
float cx, cy, cw, ch;
float vhall, hhall;
int sw, sh;
int h;
int i;
int score = 0;
  float terx, tery, terw, terh;
  float cerx, cery, cerw, cerh;
  boolean fce;
int ancientT = 0; 
boolean cont;
